// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PortalQuest.Persistence.Context;

#nullable disable

namespace PortalQuest.Persistence.Migrations
{
    [DbContext(typeof(PortalQuestDbContext))]
    [Migration("20251202104535_Core")]
    partial class Core
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PortalQuest.Domain.Entities.Core.Class", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("PortalQuest.Domain.Entities.Core.Component", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Components");
                });

            modelBuilder.Entity("PortalQuest.Domain.Entities.Core.Condition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Conditions");
                });

            modelBuilder.Entity("PortalQuest.Domain.Entities.Core.DamageType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DamageType");
                });

            modelBuilder.Entity("PortalQuest.Domain.Entities.Core.M2M.SpellClass", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SpellId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("SpellId");

                    b.ToTable("SpellClass");
                });

            modelBuilder.Entity("PortalQuest.Domain.Entities.Core.M2M.SpellTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("SpellId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SpellId");

                    b.HasIndex("TagId");

                    b.ToTable("SpellTag");
                });

            modelBuilder.Entity("PortalQuest.Domain.Entities.Core.Spell", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int?>("AttackType")
                        .HasColumnType("integer");

                    b.Property<string>("CastingTime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Concentration")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ConditionId")
                        .HasColumnType("uuid");

                    b.Property<string>("DamageDices")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("DamageType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<int>("MagicSchool")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Range")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Ritual")
                        .HasColumnType("boolean");

                    b.Property<int?>("Save")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ConditionId");

                    b.ToTable("Spells");
                });

            modelBuilder.Entity("PortalQuest.Domain.Entities.Core.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("PortalQuest.Domain.Entities.Core.M2M.SpellClass", b =>
                {
                    b.HasOne("PortalQuest.Domain.Entities.Core.Class", "Class")
                        .WithMany("SpellClasses")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortalQuest.Domain.Entities.Core.Spell", "Spell")
                        .WithMany("SpellClasses")
                        .HasForeignKey("SpellId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Spell");
                });

            modelBuilder.Entity("PortalQuest.Domain.Entities.Core.M2M.SpellTag", b =>
                {
                    b.HasOne("PortalQuest.Domain.Entities.Core.Spell", "Spell")
                        .WithMany("SpellTags")
                        .HasForeignKey("SpellId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortalQuest.Domain.Entities.Core.Tag", "Tag")
                        .WithMany("SpellTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Spell");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("PortalQuest.Domain.Entities.Core.Spell", b =>
                {
                    b.HasOne("PortalQuest.Domain.Entities.Core.Condition", "Condition")
                        .WithMany()
                        .HasForeignKey("ConditionId");

                    b.Navigation("Condition");
                });

            modelBuilder.Entity("PortalQuest.Domain.Entities.Core.Class", b =>
                {
                    b.Navigation("SpellClasses");
                });

            modelBuilder.Entity("PortalQuest.Domain.Entities.Core.Spell", b =>
                {
                    b.Navigation("SpellClasses");

                    b.Navigation("SpellTags");
                });

            modelBuilder.Entity("PortalQuest.Domain.Entities.Core.Tag", b =>
                {
                    b.Navigation("SpellTags");
                });
#pragma warning restore 612, 618
        }
    }
}
