// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PortalQuest.Persistence.Context;

#nullable disable

namespace PortalQuest.Persistence.Migrations
{
    [DbContext(typeof(PortalQuestDbContext))]
    [Migration("20260716175457_Spell-Owned-Entity")]
    partial class SpellOwnedEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EffectSpell", b =>
                {
                    b.Property<Guid>("ConditionsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SpellsId")
                        .HasColumnType("uuid");

                    b.HasKey("ConditionsId", "SpellsId");

                    b.HasIndex("SpellsId");

                    b.ToTable("EffectSpell");
                });

            modelBuilder.Entity("PortalQuest.Domain.Entities.Common.Log", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Dateime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("PortalQuest.Domain.Entities.Core.BaseCoreEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("BaseCoreEntity");
                });

            modelBuilder.Entity("PortalQuest.Domain.Entities.Core.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("PublishedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("PortalQuest.Domain.Entities.Core.Class", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("BasicRules")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("NameInSRD")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("SRD")
                        .HasColumnType("boolean");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid");

                    b.Property<int>("SourcePage")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SourceId");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("PortalQuest.Domain.Entities.Core.ClassFeature", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("BasicRules")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("NameInSRD")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("SRD")
                        .HasColumnType("boolean");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid");

                    b.Property<int>("SourcePage")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("SourceId");

                    b.ToTable("ClassFeature");
                });

            modelBuilder.Entity("PortalQuest.Domain.Entities.Core.Effect", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("BasicRules")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("SRD")
                        .HasColumnType("boolean");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid");

                    b.Property<int>("SourcePage")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SourceId");

                    b.ToTable("Effects");
                });

            modelBuilder.Entity("PortalQuest.Domain.Entities.Core.M2M.SpellClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("ClassId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsVariant")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("SourceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SpellId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("SourceId");

                    b.HasIndex("SpellId");

                    b.ToTable("SpellClass");
                });

            modelBuilder.Entity("PortalQuest.Domain.Entities.Core.Spell", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<int[]>("AbilityCheck")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<bool>("BasicRules")
                        .HasColumnType("boolean");

                    b.Property<bool>("Concentration")
                        .HasColumnType("boolean");

                    b.PrimitiveCollection<int[]>("DamageType")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<bool>("Material")
                        .HasColumnType("boolean");

                    b.Property<bool?>("MaterialConsume")
                        .HasColumnType("boolean");

                    b.Property<int?>("MaterialCost")
                        .HasColumnType("integer");

                    b.Property<string>("NameInSRD")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Ritual")
                        .HasColumnType("boolean");

                    b.Property<bool>("SRD")
                        .HasColumnType("boolean");

                    b.PrimitiveCollection<int[]>("SavingThrow")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<int>("School")
                        .HasColumnType("integer");

                    b.Property<bool>("Somatic")
                        .HasColumnType("boolean");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid");

                    b.Property<int>("SourcePage")
                        .HasColumnType("integer");

                    b.Property<bool>("Verbal")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("SourceId");

                    b.ToTable("Spells");
                });

            modelBuilder.Entity("PortalQuest.Domain.Entities.Core.SubClass", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("BasicRules")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ClassId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("NameInSRD")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("SRD")
                        .HasColumnType("boolean");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid");

                    b.Property<int>("SourcePage")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("SourceId");

                    b.ToTable("SubClass");
                });

            modelBuilder.Entity("PortalQuest.Domain.Entities.Core.Translations.BookTranslation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("LanguageCode")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OriginId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OriginId");

                    b.ToTable("BookTranslation");
                });

            modelBuilder.Entity("PortalQuest.Domain.Entities.Core.Translations.ClassFeatureTranslation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("LanguageCode")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OriginId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OriginId");

                    b.ToTable("ClassFeatureTranslation");
                });

            modelBuilder.Entity("PortalQuest.Domain.Entities.Core.Translations.ClassTranslation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("LanguageCode")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OriginId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OriginId");

                    b.ToTable("ClassTranslation");
                });

            modelBuilder.Entity("PortalQuest.Domain.Entities.Core.Translations.EffectTranslation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("LanguageCode")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OriginId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OriginId");

                    b.ToTable("EffectTranslation");
                });

            modelBuilder.Entity("PortalQuest.Domain.Entities.Core.Translations.SpellTranslation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("LanguageCode")
                        .HasColumnType("integer");

                    b.Property<string>("MaterialDescription")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OriginId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OriginId");

                    b.ToTable("SpellTranslation");
                });

            modelBuilder.Entity("PortalQuest.Domain.Entities.Core.Translations.SubClassTranslation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("LanguageCode")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OriginId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OriginId");

                    b.ToTable("SubClassTranslation");
                });

            modelBuilder.Entity("EffectSpell", b =>
                {
                    b.HasOne("PortalQuest.Domain.Entities.Core.Effect", null)
                        .WithMany()
                        .HasForeignKey("ConditionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortalQuest.Domain.Entities.Core.Spell", null)
                        .WithMany()
                        .HasForeignKey("SpellsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PortalQuest.Domain.Entities.Core.Class", b =>
                {
                    b.HasOne("PortalQuest.Domain.Entities.Core.Book", "Source")
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Source");
                });

            modelBuilder.Entity("PortalQuest.Domain.Entities.Core.ClassFeature", b =>
                {
                    b.HasOne("PortalQuest.Domain.Entities.Core.Class", "Class")
                        .WithMany("Features")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortalQuest.Domain.Entities.Core.Book", "Source")
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("PortalQuest.Domain.Entities.Core.Effect", b =>
                {
                    b.HasOne("PortalQuest.Domain.Entities.Core.Book", "Source")
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Source");
                });

            modelBuilder.Entity("PortalQuest.Domain.Entities.Core.M2M.SpellClass", b =>
                {
                    b.HasOne("PortalQuest.Domain.Entities.Core.Class", "Class")
                        .WithMany("SpellClasses")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortalQuest.Domain.Entities.Core.Book", "DefinedInSource")
                        .WithMany()
                        .HasForeignKey("SourceId");

                    b.HasOne("PortalQuest.Domain.Entities.Core.Spell", "Spell")
                        .WithMany("SpellClasses")
                        .HasForeignKey("SpellId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("DefinedInSource");

                    b.Navigation("Spell");
                });

            modelBuilder.Entity("PortalQuest.Domain.Entities.Core.Spell", b =>
                {
                    b.HasOne("PortalQuest.Domain.Entities.Core.Book", "Source")
                        .WithMany("Spells")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("PortalQuest.Domain.Entities.Core.Duration", "Durations", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<string>("Ends")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<Guid>("SpellId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Type")
                                .HasColumnType("integer");

                            b1.HasKey("Id");

                            b1.HasIndex("SpellId");

                            b1.ToTable("SpellDurations", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("SpellId");

                            b1.OwnsOne("PortalQuest.Domain.Entities.Core.Time", "Time", b2 =>
                                {
                                    b2.Property<Guid>("DurationId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("Amount")
                                        .HasColumnType("integer");

                                    b2.Property<string>("Condition")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<int>("Type")
                                        .HasColumnType("integer");

                                    b2.HasKey("DurationId");

                                    b2.ToTable("SpellDurations");

                                    b2.WithOwner()
                                        .HasForeignKey("DurationId");
                                });

                            b1.Navigation("Time");
                        });

                    b.OwnsOne("PortalQuest.Domain.Entities.Core.Range", "Range", b1 =>
                        {
                            b1.Property<Guid>("SpellId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Amount")
                                .HasColumnType("integer")
                                .HasColumnName("Range_Amount");

                            b1.Property<int>("DistanceType")
                                .HasColumnType("integer")
                                .HasColumnName("Range_DistanceType");

                            b1.Property<int>("Type")
                                .HasColumnType("integer")
                                .HasColumnName("Range_Type");

                            b1.HasKey("SpellId");

                            b1.ToTable("Spells");

                            b1.WithOwner()
                                .HasForeignKey("SpellId");
                        });

                    b.OwnsMany("PortalQuest.Domain.Entities.Core.Time", "CastingTimes", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<int>("Amount")
                                .HasColumnType("integer");

                            b1.Property<string>("Condition")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<Guid>("SpellId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Type")
                                .HasColumnType("integer");

                            b1.HasKey("Id");

                            b1.HasIndex("SpellId");

                            b1.ToTable("SpellCastingTimes", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("SpellId");
                        });

                    b.Navigation("CastingTimes");

                    b.Navigation("Durations");

                    b.Navigation("Range")
                        .IsRequired();

                    b.Navigation("Source");
                });

            modelBuilder.Entity("PortalQuest.Domain.Entities.Core.SubClass", b =>
                {
                    b.HasOne("PortalQuest.Domain.Entities.Core.Class", null)
                        .WithMany("Subs")
                        .HasForeignKey("ClassId");

                    b.HasOne("PortalQuest.Domain.Entities.Core.Book", "Source")
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Source");
                });

            modelBuilder.Entity("PortalQuest.Domain.Entities.Core.Translations.BookTranslation", b =>
                {
                    b.HasOne("PortalQuest.Domain.Entities.Core.Book", "Origin")
                        .WithMany("Translations")
                        .HasForeignKey("OriginId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Origin");
                });

            modelBuilder.Entity("PortalQuest.Domain.Entities.Core.Translations.ClassFeatureTranslation", b =>
                {
                    b.HasOne("PortalQuest.Domain.Entities.Core.ClassFeature", "Origin")
                        .WithMany("Translations")
                        .HasForeignKey("OriginId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Origin");
                });

            modelBuilder.Entity("PortalQuest.Domain.Entities.Core.Translations.ClassTranslation", b =>
                {
                    b.HasOne("PortalQuest.Domain.Entities.Core.Class", "Origin")
                        .WithMany("Translations")
                        .HasForeignKey("OriginId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Origin");
                });

            modelBuilder.Entity("PortalQuest.Domain.Entities.Core.Translations.EffectTranslation", b =>
                {
                    b.HasOne("PortalQuest.Domain.Entities.Core.Effect", "Origin")
                        .WithMany("Translations")
                        .HasForeignKey("OriginId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Origin");
                });

            modelBuilder.Entity("PortalQuest.Domain.Entities.Core.Translations.SpellTranslation", b =>
                {
                    b.HasOne("PortalQuest.Domain.Entities.Core.Spell", "Origin")
                        .WithMany("Translations")
                        .HasForeignKey("OriginId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Origin");
                });

            modelBuilder.Entity("PortalQuest.Domain.Entities.Core.Translations.SubClassTranslation", b =>
                {
                    b.HasOne("PortalQuest.Domain.Entities.Core.SubClass", "Origin")
                        .WithMany("Translations")
                        .HasForeignKey("OriginId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Origin");
                });

            modelBuilder.Entity("PortalQuest.Domain.Entities.Core.Book", b =>
                {
                    b.Navigation("Spells");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("PortalQuest.Domain.Entities.Core.Class", b =>
                {
                    b.Navigation("Features");

                    b.Navigation("SpellClasses");

                    b.Navigation("Subs");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("PortalQuest.Domain.Entities.Core.ClassFeature", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("PortalQuest.Domain.Entities.Core.Effect", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("PortalQuest.Domain.Entities.Core.Spell", b =>
                {
                    b.Navigation("SpellClasses");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("PortalQuest.Domain.Entities.Core.SubClass", b =>
                {
                    b.Navigation("Translations");
                });
#pragma warning restore 612, 618
        }
    }
}
