// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PortalQuest.Persistence.Context;

#nullable disable

namespace PortalQuest.Persistence.Migrations
{
    [DbContext(typeof(PortalQuestDbContext))]
    [Migration("20260101182530_Core")]
    partial class Core
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PortalQuest.Domain.Entities.Core.BaseCoreEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("BaseCoreEntity");
                });

            modelBuilder.Entity("PortalQuest.Domain.Entities.Core.Class", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("PortalQuest.Domain.Entities.Core.Component", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("MaterialId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Somatic")
                        .HasColumnType("boolean");

                    b.Property<bool>("Verbal")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId");

                    b.ToTable("Components");
                });

            modelBuilder.Entity("PortalQuest.Domain.Entities.Core.Condition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Conditions");
                });

            modelBuilder.Entity("PortalQuest.Domain.Entities.Core.DamageType", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DamageTypes");
                });

            modelBuilder.Entity("PortalQuest.Domain.Entities.Core.Duration", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<List<string>>("Ends")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("TimeId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TimeId");

                    b.ToTable("Durations");
                });

            modelBuilder.Entity("PortalQuest.Domain.Entities.Core.M2M.SpellClass", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SpellId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("SpellId");

                    b.ToTable("SpellClass");
                });

            modelBuilder.Entity("PortalQuest.Domain.Entities.Core.Material", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("Consume")
                        .HasColumnType("boolean");

                    b.Property<int>("Cost")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Materials");
                });

            modelBuilder.Entity("PortalQuest.Domain.Entities.Core.Range", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.Property<int>("DistanceType")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Ranges");
                });

            modelBuilder.Entity("PortalQuest.Domain.Entities.Core.Source", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Sources");
                });

            modelBuilder.Entity("PortalQuest.Domain.Entities.Core.Spell", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<int[]>("AbilityCheck")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<Guid>("ComponentsId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Concentration")
                        .HasColumnType("boolean");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<int[]>("DamageType")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<Guid>("DurationId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RangeId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Ritual")
                        .HasColumnType("boolean");

                    b.Property<bool>("SRD")
                        .HasColumnType("boolean");

                    b.PrimitiveCollection<int[]>("SavingThrow")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<int>("School")
                        .HasColumnType("integer");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid");

                    b.Property<int>("SourcePage")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ComponentsId");

                    b.HasIndex("DurationId");

                    b.HasIndex("RangeId");

                    b.HasIndex("SourceId");

                    b.ToTable("Spells");
                });

            modelBuilder.Entity("PortalQuest.Domain.Entities.Core.Time", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("SpellId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SpellId");

                    b.ToTable("Times");
                });

            modelBuilder.Entity("PortalQuest.Domain.Entities.Core.Component", b =>
                {
                    b.HasOne("PortalQuest.Domain.Entities.Core.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId");

                    b.Navigation("Material");
                });

            modelBuilder.Entity("PortalQuest.Domain.Entities.Core.Duration", b =>
                {
                    b.HasOne("PortalQuest.Domain.Entities.Core.Time", "Time")
                        .WithMany()
                        .HasForeignKey("TimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Time");
                });

            modelBuilder.Entity("PortalQuest.Domain.Entities.Core.M2M.SpellClass", b =>
                {
                    b.HasOne("PortalQuest.Domain.Entities.Core.Class", "Class")
                        .WithMany("SpellClasses")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortalQuest.Domain.Entities.Core.Spell", "Spell")
                        .WithMany("SpellClasses")
                        .HasForeignKey("SpellId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Spell");
                });

            modelBuilder.Entity("PortalQuest.Domain.Entities.Core.Spell", b =>
                {
                    b.HasOne("PortalQuest.Domain.Entities.Core.Component", "Components")
                        .WithMany()
                        .HasForeignKey("ComponentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortalQuest.Domain.Entities.Core.Duration", "Duration")
                        .WithMany()
                        .HasForeignKey("DurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortalQuest.Domain.Entities.Core.Range", "Range")
                        .WithMany()
                        .HasForeignKey("RangeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortalQuest.Domain.Entities.Core.Source", "Source")
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Components");

                    b.Navigation("Duration");

                    b.Navigation("Range");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("PortalQuest.Domain.Entities.Core.Time", b =>
                {
                    b.HasOne("PortalQuest.Domain.Entities.Core.Spell", null)
                        .WithMany("CastingTime")
                        .HasForeignKey("SpellId");
                });

            modelBuilder.Entity("PortalQuest.Domain.Entities.Core.Class", b =>
                {
                    b.Navigation("SpellClasses");
                });

            modelBuilder.Entity("PortalQuest.Domain.Entities.Core.Spell", b =>
                {
                    b.Navigation("CastingTime");

                    b.Navigation("SpellClasses");
                });
#pragma warning restore 612, 618
        }
    }
}
