// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PortalQuest.Persistence.Context;

#nullable disable

namespace PortalQuest.Persistence.Migrations
{
    [DbContext(typeof(PortalQuestDbContext))]
    [Migration("20260311170912_Effect")]
    partial class Effect
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DurationSpell", b =>
                {
                    b.Property<Guid>("DurationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SpellsId")
                        .HasColumnType("uuid");

                    b.HasKey("DurationId", "SpellsId");

                    b.HasIndex("SpellsId");

                    b.ToTable("DurationSpell");
                });

            modelBuilder.Entity("PortalQuest.Domain.Entities.Common.Log", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Dateime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("PortalQuest.Domain.Entities.Core.BaseCoreEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("BaseCoreEntity");
                });

            modelBuilder.Entity("PortalQuest.Domain.Entities.Core.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("PublishedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("PortalQuest.Domain.Entities.Core.Class", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SourceId");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("PortalQuest.Domain.Entities.Core.ClassFeature", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.ToTable("ClassFeature");
                });

            modelBuilder.Entity("PortalQuest.Domain.Entities.Core.Duration", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<List<string>>("Ends")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("TimeId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TimeId");

                    b.ToTable("Durations");
                });

            modelBuilder.Entity("PortalQuest.Domain.Entities.Core.Effect", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("BasicRules")
                        .HasColumnType("boolean");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("SRD")
                        .HasColumnType("boolean");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid");

                    b.Property<int>("SourcePage")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SourceId");

                    b.ToTable("Effects");
                });

            modelBuilder.Entity("PortalQuest.Domain.Entities.Core.M2M.SpellClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("ClassId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsVariant")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("SourceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SpellId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("SourceId");

                    b.HasIndex("SpellId");

                    b.ToTable("SpellClass");
                });

            modelBuilder.Entity("PortalQuest.Domain.Entities.Core.Range", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.Property<int>("DistanceType")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Ranges");
                });

            modelBuilder.Entity("PortalQuest.Domain.Entities.Core.Spell", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<int[]>("AbilityCheck")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<bool>("BasicRules")
                        .HasColumnType("boolean");

                    b.Property<bool>("Concentration")
                        .HasColumnType("boolean");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<int[]>("DamageType")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<bool>("Material")
                        .HasColumnType("boolean");

                    b.Property<bool?>("MaterialConsume")
                        .HasColumnType("boolean");

                    b.Property<int?>("MaterialCost")
                        .HasColumnType("integer");

                    b.Property<string>("MaterialDescription")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NameInSRD")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RangeId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Ritual")
                        .HasColumnType("boolean");

                    b.Property<bool>("SRD")
                        .HasColumnType("boolean");

                    b.PrimitiveCollection<int[]>("SavingThrow")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<int>("School")
                        .HasColumnType("integer");

                    b.Property<bool>("Somatic")
                        .HasColumnType("boolean");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid");

                    b.Property<int>("SourcePage")
                        .HasColumnType("integer");

                    b.Property<bool>("Verbal")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("RangeId");

                    b.HasIndex("SourceId");

                    b.ToTable("Spells");
                });

            modelBuilder.Entity("PortalQuest.Domain.Entities.Core.SubClass", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ClassId")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.ToTable("SubClass");
                });

            modelBuilder.Entity("PortalQuest.Domain.Entities.Core.Time", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Times");
                });

            modelBuilder.Entity("SpellTime", b =>
                {
                    b.Property<Guid>("CastingTimeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SpellsId")
                        .HasColumnType("uuid");

                    b.HasKey("CastingTimeId", "SpellsId");

                    b.HasIndex("SpellsId");

                    b.ToTable("SpellTime");
                });

            modelBuilder.Entity("DurationSpell", b =>
                {
                    b.HasOne("PortalQuest.Domain.Entities.Core.Duration", null)
                        .WithMany()
                        .HasForeignKey("DurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortalQuest.Domain.Entities.Core.Spell", null)
                        .WithMany()
                        .HasForeignKey("SpellsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PortalQuest.Domain.Entities.Core.Class", b =>
                {
                    b.HasOne("PortalQuest.Domain.Entities.Core.Book", "Source")
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Source");
                });

            modelBuilder.Entity("PortalQuest.Domain.Entities.Core.ClassFeature", b =>
                {
                    b.HasOne("PortalQuest.Domain.Entities.Core.Class", "Class")
                        .WithMany("Features")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");
                });

            modelBuilder.Entity("PortalQuest.Domain.Entities.Core.Duration", b =>
                {
                    b.HasOne("PortalQuest.Domain.Entities.Core.Time", "Time")
                        .WithMany("Durations")
                        .HasForeignKey("TimeId");

                    b.Navigation("Time");
                });

            modelBuilder.Entity("PortalQuest.Domain.Entities.Core.Effect", b =>
                {
                    b.HasOne("PortalQuest.Domain.Entities.Core.Book", "Source")
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Source");
                });

            modelBuilder.Entity("PortalQuest.Domain.Entities.Core.M2M.SpellClass", b =>
                {
                    b.HasOne("PortalQuest.Domain.Entities.Core.Class", "Class")
                        .WithMany("SpellClasses")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortalQuest.Domain.Entities.Core.Book", "DefinedInSource")
                        .WithMany()
                        .HasForeignKey("SourceId");

                    b.HasOne("PortalQuest.Domain.Entities.Core.Spell", "Spell")
                        .WithMany("SpellClasses")
                        .HasForeignKey("SpellId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("DefinedInSource");

                    b.Navigation("Spell");
                });

            modelBuilder.Entity("PortalQuest.Domain.Entities.Core.Spell", b =>
                {
                    b.HasOne("PortalQuest.Domain.Entities.Core.Range", "Range")
                        .WithMany("Spells")
                        .HasForeignKey("RangeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortalQuest.Domain.Entities.Core.Book", "Source")
                        .WithMany("Spells")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Range");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("PortalQuest.Domain.Entities.Core.SubClass", b =>
                {
                    b.HasOne("PortalQuest.Domain.Entities.Core.Class", null)
                        .WithMany("Subs")
                        .HasForeignKey("ClassId");
                });

            modelBuilder.Entity("SpellTime", b =>
                {
                    b.HasOne("PortalQuest.Domain.Entities.Core.Time", null)
                        .WithMany()
                        .HasForeignKey("CastingTimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortalQuest.Domain.Entities.Core.Spell", null)
                        .WithMany()
                        .HasForeignKey("SpellsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PortalQuest.Domain.Entities.Core.Book", b =>
                {
                    b.Navigation("Spells");
                });

            modelBuilder.Entity("PortalQuest.Domain.Entities.Core.Class", b =>
                {
                    b.Navigation("Features");

                    b.Navigation("SpellClasses");

                    b.Navigation("Subs");
                });

            modelBuilder.Entity("PortalQuest.Domain.Entities.Core.Range", b =>
                {
                    b.Navigation("Spells");
                });

            modelBuilder.Entity("PortalQuest.Domain.Entities.Core.Spell", b =>
                {
                    b.Navigation("SpellClasses");
                });

            modelBuilder.Entity("PortalQuest.Domain.Entities.Core.Time", b =>
                {
                    b.Navigation("Durations");
                });
#pragma warning restore 612, 618
        }
    }
}
